# Setup
title:               kimbeomjoon99
tagline:             'PS, daily, etc.'
description:         '집가고싶다'
url:                 https://kimbeomjoon99.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Beomjoon Kim
  url:               https://github.com/kimbeomjoon99
  email:             tnldls99@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
